version: '3'
services:
  letsencrypt:
    image: linuxserver/swag
    container_name: letsencrypt
    environment: 
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - URL=sandeshpractise.tk
      - SUBDOMAINS=www
      - VALIDATION=dns
      - DNSPLUGIN=route53
      - EMAIL=sandeshpokhrel17@gmail.com
      - DHLEVEL=4096
    volumes: 
      - ./config:/config 
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "443:443" 
      - "80:80"
    depends_on:
      - api
      - client 
    volumes:
      - ./config/certs:/etc/ssl/private
  db:
    restart: unless-stopped
    image: 'mongo:latest'
    ports: 
      - 27017:27017
    volumes: 
      - /data:/data/db
  client:
    container_name: client
    stdin_open: true
    image: pokhrelsandesh27/new-front:0.1
      
  api:
    container_name: api
    build: 
      dockerfile: Dockerfile
      context: ./server
 # mongo-seed:
 #   image: mongo:3.2.6
 #   #links:
 #   #  - db
 #   build: 
 #     dockerfile: Dockerfile
 #     context: ./mongo-seed
  
  
  
    

    
