version: '3'
services:
  letsencrypt:
    image: linuxserver/swag
    container_name: letsencrypt
    environment: 
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - URL=
      - SUBDOMAINS=
      - VALIDATION=dns
      - DNSPLUGIN=route53
      - EMAIL=everestwalk123@gmail.com
      - DHLEVEL=4096
    volumes: 
      - ./config:/config 
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports: 
      - "80:80"
    depends_on:
      - api
      - client 
  #db:
   # restart: unless-stopped
   # image: 'mongo:latest'
   # ports: 
   #   - 27017:27017
   # volumes: 
   #   - /data:/data/db
  client:
    container_name: client
    stdin_open: true
    image: pokhrelsandesh27/new-front
      
  api:
    container_name: api
    build: 
      dockerfile: Dockerfile
      context: ./server
 # mongo-seed:
 #   image: mongo:3.2.6
 #   #links:
 #   #  - db
 #   build: 
 #     dockerfile: Dockerfile
 #     context: ./mongo-seed
  
  
  
    

    